const styles = {
    rootContainer: {
      width: '100vw',
      height: '100vh',
      backgroundColor: '#1a1025',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      fontFamily: 'Arial, sans-serif',
      color: '#000000',
      position: 'relative',
      overflow: 'hidden',
    },
    backgroundOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      zIndex: 1,
      backgroundImage: 'url(https://play.rosebud.ai/assets/bg-main.png?Xrrp)',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center',
      backgroundSize: 'cover',
      opacity: 0.95,
    },
    contentContainer: {
      width: '85%',
      position: 'relative',
      zIndex: 2,
      minHeight: '85vh',
      maxHeight: '85vh',
      padding: '2rem',
      overflowY: 'auto',
      overflowX: 'hidden',
      backgroundColor: '#120B1C',
      borderRadius: '10px',
      boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
      boxSizing: 'border-box',
    },
    searchContainer: {
      display: 'flex',
      gap: '8px',
      marginBottom: '20px',
      width: '100%',
    },
    searchInputWrapper: {
      position: 'relative',
      flex: 1,
    },
    searchInput: {
      width: '100%',
      padding: '12px 16px',
      boxSizing: 'border-box',
      fontSize: '16px',
      border: '1px solid #8A2BE2',
      borderRadius: '8px',
      outline: 'none',
      transition: 'border-color 0.2s ease',
      backgroundColor: '#1a1025',
      color: '#fff',
    },
    searchResults: {
      position: 'absolute',
      top: '100%',
      left: 0,
      right: 0,
      backgroundColor: '#1a1025',
      border: '1px solid #8A2BE2',
      borderRadius: '8px',
      marginTop: '4px',
      maxHeight: '200px',
      overflowY: 'auto',
      zIndex: 10,
    },
    searchResultButton: {
      width: '100%',
      padding: '12px 16px',
      backgroundColor: 'transparent',
      border: 'none',
      borderBottom: '1px solid rgba(138, 43, 226, 0.2)',
      color: '#fff',
      textAlign: 'left',
      cursor: 'pointer',
      fontSize: '14px',
      transition: 'background-color 0.2s ease',
    },
    searchIcon: {
      padding: '12px 20px',
      fontSize: '16px',
      backgroundColor: '#8A2BE2',
      color: '#ffffff',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    qaContainer: {
      marginTop: '1rem',
      marginBottom: '2rem',
      padding: '1.5rem',
      backgroundColor: 'rgba(138, 43, 226, 0.1)',
      borderRadius: '12px',
      border: '1px solid rgba(138, 43, 226, 0.3)',
      animation: 'fadeIn 0.3s ease-in-out',
    },
    question: {
      color: '#E4B5FF',
      fontSize: '1.5rem',
      marginBottom: '1rem',
      fontWeight: '600',
      lineHeight: '1.4',
    },
    answer: {
      color: '#ffffff',
      fontSize: '1.1rem',
      lineHeight: '1.6',
      marginBottom: '1rem',
      whiteSpace: 'pre-wrap',
    },
    relatedSection: {
      marginTop: '1rem',
      paddingTop: '0.5rem',
    },
    relatedTitle: {
      color: '#E4B5FF',
      fontSize: '1.2rem',
      marginBottom: '1rem',
      fontWeight: '500',
    },
    relatedList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '0.8rem',
    },
    relatedButton: {
      padding: '1rem',
      backgroundColor: 'rgba(138, 43, 226, 0.1)',
      border: '1px solid rgba(138, 43, 226, 0.3)',
      borderRadius: '8px',
      color: '#ffffff',
      textAlign: 'left',
      cursor: 'pointer',
      fontSize: '1rem',
      transition: 'all 0.2s ease',
      fontWeight: '400',
      lineHeight: '1.4',
      width: '100%',
    },
    searchSection: {
      width: '100%',
      marginTop: '1rem',
      marginBottom: '1rem',
      display: 'flex',
      justifyContent: 'center'
    },
    questionContainer: {
      width: '100%',
      maxWidth: '100%',
      padding: '1.5rem',
      marginBottom: '2rem',
      backgroundColor: 'rgba(138, 43, 226, 0.1)',
      borderRadius: '8px',
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
      boxSizing: 'border-box',
      overflow: 'hidden'
    },
    answerContainer: {
      width: '100%',
      maxWidth: '100%',
      padding: '1rem',
      marginBottom: '1rem',
      backgroundColor: 'rgba(138, 43, 226, 0.1)',
      borderRadius: '8px',
      boxShadow: '0 4px 6px rgba(138, 43, 226, 0.05)',
      border: '1px solid rgba(138, 43, 226, 0.15)',
      boxSizing: 'border-box',
      position: 'relative',
      transition: 'all 0.3s ease'
    }
  };
export default styles;